name: badr_agri
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  drift: ^2.20.3
  drift_flutter: ^0.2.0
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  sqlite3_flutter_libs: ^0.5.24
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  supabase_auth_ui: ^0.5.2
  supabase_flutter: ^2.7.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  drift_dev: ^2.20.3

flutter:
  uses-material-design: true
  assets : 
   - assets/logo.png

